main: com.cavetale.halloween.HalloweenPlugin
name: Halloween
version: 0.1
api-version: 1.17
description: Halloween
author: StarTux
website: https://cavetale.com
depend: [Dungeons, Dirty, WorldMarker, Mytems, Money]
softdepend: []
commands:
  halloween:
    description: Halloween
    permission: halloween.halloween
    usage: /<command>
  maskcollector:
    description: Mask collection
permissions:
  halloween.halloween:
    description: Use /halloween
